;1.9
(define (+ a b)
    (if (= a 0) b (inc (+ (dec a) b))))
(define (+ a b)
    (if (= a 0) b (+ (dec a) (inc b))))
; using the substitution model, illustrate the process generated by each procedure in evaluating
; (+ 4 5). Are these processes iterative or recursive
; 1st definition
; (+ 4 5)
; (inc (+ (dec 4) 5))
; (inc (+ 3 5))
; (inc (inc (+ (dec 3) 5))) 
; (inc (inc (+ 2 5))) 
; (inc (inc (inc (+ (dec 2) 5))))
; (inc (inc (inc (+ 1 5))))
; (inc (inc (inc (inc (+ (dec 1) 5)))))
; (inc (inc (inc (inc (+ 0 5)))))
; (inc (inc (inc (inc (5)))))
; (inc (inc (inc (6)))
; (inc (inc (7)))
; (inc (8))
; 9
; 2nd definition
; (+ 4 5)
; (+ (dec 4) (inc 5))
; (+ (3) (6))
; (+ (dec 3) (inc 6))
; (+ (2) (7))
; (+ (dec 2) (inc 7))
; (+ (1) (8))
; (+ (dec 1) (inc 8))
; (+ (0) (9))
; 9

;1.10
(define (A x y) 
    (cond ((= y 0) 0)
        ((= x 0) (* 2 y))
        ((= y 1) 2)
        (else (A (- x 1) (A x (- y 1))))))
  
; what are the values of the following expressions?
(A 1 10)
;A (0) (A (1) (9))
;A (0) (A (0) (A (1) (8))
;A (0) (A (0) (A (0) (A (1) (7)))
;A (0) (A (0) (A (0) (A (0) (A (1) (6))))
;A (0) (A (0) (A (0) (A (0) (A (0) (A (1) (5)))))
;A (0) (A (0) (A (0) (A (0) (A (0) (A (0) (A (1) (4)))))
;A (0) (A (0) (A (0) (A (0) (A (0) (A (0) (A(0) (A (1) (3))))))
;A (0) (A (0) (A (0) (A (0) (A (0) (A (0) (A(0) (A (0) (A (1) (2)))))))
;A (0) (A (0) (A (0) (A (0) (A (0) (A (0) (A(0) (A (0) (A (0) (A (1) (0)))))))
;A (0) (A (0) (A (0) (A (0) (A (0) (A (0) (A(0) (A (0) (A (0) (2))))))
;A (0) (A (0) (A (0) (A (0) (A (0) (A (0) (A(0) (A (0) (4))))))
;A (0) (A (0) (A (0) (A (0) (A (0) (A (0) (A(0) (8))))))
;A (0) (A (0) (A (0) (A (0) (A (0) (A (0) (16)))))
;A (0) (A (0) (A (0) (A (0) (A (0) (32)))))
;A (0) (A (0) (A (0) (A (0) (64)))))
;A (0) (A (0) (A (0) (128)))))
;A (0) (A (0) (256)))
;A (0) (512))
;1024

(A 2 4)
;(A (1) (A (2) (3))
;(A (1) (A (1) (A (2) (2)))
;(A (1) (A (1) (A (1) (A (2)(1))))
;(A (1) (A (1) (A (1) (2))))
;(A (1) (A (1) (A (1) (A (0) (A (1) (1))))))
;(A (1) (A (1) (A (1) (A (0) (2)))))
;(A (1) (A (1) (A (1) (4)))))
;(A (1) (A (1) (A (1) (4))))
;(A (1) (A (1) (A (0) (A (1) (3)))))
;(A (1) (A (1) (A (0) (A (0) (A (1) (2)))))
;(A (1) (A (1) (A (0) (A (0) (A (0) (A (1) (1))))))
;(A (1) (A (1) (A (0) (A (0) (A (0) (2)))))
;(A (1) (A (1) (A (0) (A (0) (4))))))
;(A (1) (A (1) (16)))))
; with an even bigger pyramid than the one above!


(A 3 3)

;give concise mathematical definitions of the following
(define (f n) (A 0 n)) ; 2n
(define (g n) (A 1 n)) ; 2^n
(define (h n) (A 2 n)) ; 2^2^2^2... n times
(define (k n) (* 5 n n)) ;5n^2