;1.9
(define (+ a b)
    (if (= a 0) b (inc (+ (dec a) b))))
(define (+ a b)
    (if (= a 0) b (+ (dec a) (inc b))))
; using the substitution model, illustrate the process generated by each procedure in evaluating
; (+ 4 5). Are these processes iterative or recursive
; 1st definition
; (+ 4 5)
; (inc (+ (dec 4) 5))
; (inc (+ 3 5))
; (inc (inc (+ (dec 3) 5))) 
; (inc (inc (+ 2 5))) 
; (inc (inc (inc (+ (dec 2) 5))))
; (inc (inc (inc (+ 1 5))))
; (inc (inc (inc (inc (+ (dec 1) 5)))))
; (inc (inc (inc (inc (+ 0 5)))))
; 2nd definition
; 